<a href="https://colab.research.google.com/github/mevangelista-alvarado/CNVSMM/blob/main/Update_CNVSMM_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `NUMERICAL POISSON GEOMETRY`

Este *notebook* fue utilizado en la charla **Un breve vistazo a la Geometría de Poisson Computacional** durante la realización del *Congreso Nacional Virtual de la Sociedad Matemática Mexicana en 2020*

Videos de la plática:
*   [Parte I](https://www.youtube.com/watch?v=27nBbz8BbL0&feature=emb_logo)
*   [Parte II](https://www.youtube.com/watch?v=PtTaK_Qef54&feature=emb_logo)



# Instalación y sintaxis
---

In [51]:
!pip install numericalpoissongeometry

### Bivector



El bivector asociado a $\mathfrak{so}(3)$ es

$$\Pi_{\mathfrak{so(3)}} = x_{3}\frac{\partial}{\partial x_{1}} \wedge \frac{\partial}{\partial x_{2}} - x_{2}\frac{\partial}{\partial x_{1}} \wedge \frac{\partial}{\partial x_{3}} + x_{1}\frac{\partial}{\partial x_{2}} \wedge \frac{\partial}{\partial x_{3}}$$


In [52]:
P_so3 = {(1, 2): 'x3', (1, 3): '-1*x2', (2, 3): 'x1'}
P_so3 = {(1, 2): 'x3', (1, 3): '-x2', (2, 3): 'x1'}

Recuerde lo siguiente para `Python`



*   `**` --> exponente
*   `*`  --> multiplicación
*   `+`  --> suma
*   `-`  --> resta
*   `/`  --> división

Más info https://docs.python.org/3/library/numeric.html


### Funciones Escalares


Sea $K_{\mathfrak{so}(3)}: \mathbb{R}^{3} \to \mathbb{R}$ definida como $$K_{\mathfrak{so}(3)}(x_{1}, x_{2}, x_{3}) = \frac{x^{2}_{1}}{2} + \frac{x^{2}_{2}}{2} + \frac{x^{2}_{3}}{2} $$


In [53]:
K_so3 = '(1/2)*(x1**2 + x2**2 + x3**2)'
K_so3 = '(x1**2)/2 + (x2**2)/2 + (x3**2)/2'

### Mallas

Las mallas que utiliza el módulo `NumericalPoissonGeometry` son las siguientes:
*   Lista de listas
*   Arreglos de `Numpy`


#### Lista de listas (`Python` nativo)

In [54]:
# Simple lista de listas en Python
R3_list = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
R3_list

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

#### Arreglos de `Numpy`

Para manipular una gran cantidad de puntos, es recomendable utilizar el módulo de `python` para análisis numérico `numpy`.

In [55]:
import numpy as np # Importamos el módulo numpy

 # Generamos un malla de 10**4 puntos con números aleatorios
R3_numpy_ramdon = np.random.rand(10**4, 3)
R3_numpy_ramdon

array([[0.53533936, 0.60865954, 0.36075538],
       [0.32688849, 0.2204368 , 0.36630328],
       [0.4661344 , 0.56215657, 0.24956744],
       ...,
       [0.48572444, 0.22866941, 0.10422987],
       [0.10564128, 0.59463767, 0.68986314],
       [0.81940783, 0.16667107, 0.65563825]])

In [56]:
len(R3_numpy_ramdon)

10000

### Primer uso del módulo

In [57]:
# Importamos el módulo NumericalPoissonGeometry
from numpoisson.numpoisson import NumPoissonGeometry as npg

# Instanciar el módulo NumericalPoissonGeometry con la dimensión y la variable a usar
npg3 = npg(3, 'x')
# Esta función muestra todos los métodos de una clase
dir(npg)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'num_bivector',
 'num_bivector_to_matrix',
 'num_coboundary_operator',
 'num_curl_operator',
 'num_flaschka_ratiu_bivector',
 'num_gauge_transformation',
 'num_hamiltonian_vf',
 'num_linear_normal_form_R3',
 'num_modular_vf',
 'num_one_forms_bracket',
 'num_poisson_bracket',
 'num_sharp_morphism']

#### $\LaTeX$ bonito

In [58]:
import sympy
def custom_latex_printer(exp,**options):
    from google.colab.output._publish import javascript
    url = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=default"
    javascript(url=url)
    return sympy.printing.latex(exp,**options)
sympy.init_printing(use_latex="mathjax",latex_printer=custom_latex_printer)

# Álgebra de Lie $\mathfrak{so}(3)$

---



Recordemos

$$\mathfrak{so}(3)\simeq\{ M \in Mat_{3\times 3}(\mathbb{R}) | M^{T} = -M \}$$  
  

La estructura de álgebra de Lie en $\{ M \in Mat_{3\times 3}(\mathbb{R}) | M^{T} = -M \}$ es la inducida por el conmutador $[A, B]:= AB - BA$

El bivector asociado a $\mathfrak{so}(3)$ es

$$\Pi_{\mathfrak{so(3)}} = x_{3}\frac{\partial}{\partial x_{1}} \wedge \frac{\partial}{\partial x_{2}} - x_{2}\frac{\partial}{\partial x_{1}} \wedge \frac{\partial}{\partial x_{3}} + x_{1}\frac{\partial}{\partial x_{2}} \wedge \frac{\partial}{\partial x_{3}}$$

### Evaluación de la matriz asociada al bivector $\Pi_{\mathfrak{so(3)}}$

In [59]:
# Importamos el módulo NumericalPoissonGeometry
from numpoisson.numpoisson import NumPoissonGeometry as npg

# Instanciamos el módulo NumericalPoissonGeometry
npg3 = npg(3, 'x')
# Definimos el bivector asociado a so(3)
P_so3 = {(1, 2): 'x3', (1, 3): '-x2', (2, 3): 'x1'}

Para el caso de la malla `R3_list`



In [60]:
R3_list

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [61]:
# Importamos el módulo PoissonGeometry
from poisson.poisson import PoissonGeometry as pg

# Instanciamos el módulo PoissonGeometry
pg3 = pg(3, 'x')
# Calculamos la matriz asociada al bivector P_so3
pg3.bivector_to_matrix(P_so3)

⎡ 0   x₃   -x₂⎤
⎢             ⎥
⎢-x₃   0   x₁ ⎥
⎢             ⎥
⎣x₂   -x₁   0 ⎦

Las funciones del método `NumericalPoissonGeometry` retornan 4 tipos de resultados:


*   `Numpy`,
*   tf_output  --->  `TensorFlow`
*   pt_output  --->  `Pytorch`
*   dict_output -->  `PoissonGeometry`



In [62]:
# Evaluamos la matriz asociada al bivector P_so3 en la malla R3_list
result_np = npg3.num_bivector_to_matrix(P_so3, R3_list)
result_np

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]],

       [[ 0.,  0., -1.],
        [ 0.,  0.,  0.],
        [ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [63]:
type(result_np)

numpy.ndarray

In [64]:
# Evaluamos la matriz asociado al bivector P_so3 en la malla R3_list
result_pt = npg3.num_bivector_to_matrix(P_so3, R3_list, torch_output=True)
result_pt

tensor([[[ 0.,  0.,  0.],
         [ 0.,  0.,  1.],
         [ 0., -1.,  0.]],

        [[ 0.,  0., -1.],
         [ 0.,  0.,  0.],
         [ 1.,  0.,  0.]],

        [[ 0.,  1.,  0.],
         [-1.,  0.,  0.],
         [ 0.,  0.,  0.]]], dtype=torch.float64)

In [65]:
type(result_pt)

torch.Tensor

In [66]:
# Evaluamos la matriz asociada al bivector P_so3 en la malla R3_list
result_tf = npg3.num_bivector_to_matrix(P_so3, R3_list, tf_output=True)
result_tf

<tf.Tensor: shape=(3, 3, 3), dtype=float64, numpy=
array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]],

       [[ 0.,  0., -1.],
        [ 0.,  0.,  0.],
        [ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0.,  0.]]])>

In [67]:
type(result_tf)

tensorflow.python.framework.ops.EagerTensor

Para el caso de la malla `R3_numpy_ramdon`

In [68]:
# Evaluamos la matriz asociada al bivector P_so3 en la malla R3_numpy_ramdon
result_np = npg3.num_bivector_to_matrix(P_so3, R3_numpy_ramdon)
result_np

array([[[ 0.        ,  0.36075538, -0.60865954],
        [-0.36075538,  0.        ,  0.53533936],
        [ 0.60865954, -0.53533936,  0.        ]],

       [[ 0.        ,  0.36630328, -0.2204368 ],
        [-0.36630328,  0.        ,  0.32688849],
        [ 0.2204368 , -0.32688849,  0.        ]],

       [[ 0.        ,  0.24956744, -0.56215657],
        [-0.24956744,  0.        ,  0.4661344 ],
        [ 0.56215657, -0.4661344 ,  0.        ]],

       ...,

       [[ 0.        ,  0.10422987, -0.22866941],
        [-0.10422987,  0.        ,  0.48572444],
        [ 0.22866941, -0.48572444,  0.        ]],

       [[ 0.        ,  0.68986314, -0.59463767],
        [-0.68986314,  0.        ,  0.10564128],
        [ 0.59463767, -0.10564128,  0.        ]],

       [[ 0.        ,  0.65563825, -0.16667107],
        [-0.65563825,  0.        ,  0.81940783],
        [ 0.16667107, -0.81940783,  0.        ]]])

### Evaluación del bivector $\Pi_{\mathfrak{so(3)}}$

In [69]:
# Evaluamos el bivector P_so3 en la malla
npg3.num_bivector(P_so3, R3_list)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]],

       [[ 0.,  0., -1.],
        [ 0.,  0.,  0.],
        [ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [70]:
# Evaluamos el bivector asociado a P_so3 en la malla R3_list
result_dict = npg3.num_bivector(P_so3, R3_list, dict_output=True)
result_dict

array([{(2, 3): 1}, {(1, 3): -1}, {(1, 2): 1}], dtype=object)

In [71]:
type(result_dict)

numpy.ndarray

#### Evaluación de $X_{h}$ relativo a $\Pi_{\mathfrak{so(3)}}$


Caso 1:

Sea $h = K_{\mathfrak{so}(3)}: \mathbb{R}^{3} \to \mathbb{R}$ definida como $$K_{\mathfrak{so}(3)}(x_{1}, x_{2}, x_{3}) = \frac{x^{2}_{1}}{2} + \frac{x^{2}_{2}}{2} + \frac{x^{2}_{3}}{2} $$


In [72]:
# Encontramos el campo vectorial asociado a K_so3 inducido por P_so3 con el módulo simbólico
pg3.hamiltonian_vf(P_so3, K_so3)

{}

In [73]:
# Evaluamos el campo vectorial en la malla R3_numpy_ramdon
npg3.num_hamiltonian_vf(P_so3, K_so3, R3_numpy_ramdon, torch_output=True)

tensor([[[ 3.5860e-18],
         [ 9.5342e-18],
         [-1.4867e-17]],

        [[-5.7782e-18],
         [ 4.3185e-18],
         [ 3.5779e-18]],

        [[ 5.7365e-18],
         [-1.7865e-19],
         [ 2.3907e-17]],

        ...,

        [[-9.9731e-19],
         [ 2.7288e-18],
         [ 5.5009e-18]],

        [[-2.6462e-17],
         [-1.0438e-18],
         [-2.8863e-18]],

        [[ 2.8433e-18],
         [ 4.9159e-17],
         [ 7.3054e-19]]], dtype=torch.float64)

Caso 2:  

Sea $h: \mathbb{R}^{3} \to \mathbb{R}$ definida como $$h(x_{1}, x_{2}, x_{3}) = \frac{x^{2}_{1}}{2} - \frac{x^{2}_{2}}{2} - \frac{x^{2}_{3}}{2} $$


In [74]:
# Definimos una función escalar h
h = '(x1**2)/2 - (x2**2)/2 - (x3**2)/2'
# Encontramos el campo vectorial asociado a K_so3 inducido por P_so3 con el módulo simbólico
pg3.hamiltonian_vf(P_so3, h)

{(2,): '2*x1*x3', (3,): '-2*x1*x2'}

In [75]:
# Evaluamos el campo vectorial en la malla R3_list
npg3.num_hamiltonian_vf(P_so3, h, R3_list)

array([[[-0.],
        [-0.],
        [-0.]],

       [[-0.],
        [-0.],
        [-0.]],

       [[-0.],
        [-0.],
        [-0.]]])

In [76]:
# Evaluamos el campo vectorial en la malla R3_numpy_ramdon
npg3.num_hamiltonian_vf(P_so3, h, R3_numpy_ramdon)

array([[[-3.58596071e-18],
        [ 3.86253109e-01],
        [-6.51678816e-01]],

       [[ 5.77817354e-18],
        [ 2.39480654e-01],
        [-1.44116505e-01]],

       [[-5.73649145e-18],
        [ 2.32663934e-01],
        [-5.24081028e-01]],

       ...,

       [[ 9.97306122e-19],
        [ 1.01253991e-01],
        [-2.22140647e-01]],

       [[ 2.64617839e-17],
        [ 1.45756050e-01],
        [-1.25636569e-01]],

       [[-2.84326348e-18],
        [ 1.07447023e+00],
        [-2.73143159e-01]]])

# Álgebra de Lie $\mathfrak{sl}(2)$

---

Recordemos

$$\mathfrak{sl}(2)\simeq\{ M \in Mat_{3\times 3}(\mathbb{R}) | tr(M) = 0 \}$$  
  

La estructura de álgebra de Lie en $\{ M \in Mat_{3\times 3}(\mathbb{R}) | tr(M) = 0 \}$ es la inducida por el conmutador $[A, B]:= AB - BA$

El bivector asociado a $\mathfrak{sl}(2)$ es

$$\Pi_{\mathfrak{sl(2)}} = - x_{3}\frac{\partial}{\partial x_{1}} \wedge \frac{\partial}{\partial x_{2}} - x_{2}\frac{\partial}{\partial x_{1}} \wedge \frac{\partial}{\partial x_{3}} + x_{1}\frac{\partial}{\partial x_{2}} \wedge \frac{\partial}{\partial x_{3}}$$

Evaluación del operador de cofrontera inducido por $\Pi_{\mathfrak{sl(2)}}$ en el campo vectorial  

$$W = \frac{x_{1} x_{3} exp^{\frac{-1}{(x_1^2 + x_2^2 - x_3^2)^{2}}}}{x_1^2 + x_2^2}\frac{\partial}{\partial x_1} + \frac{x_{2} x_{3} exp^{\frac{-1}{(x_1^2 + x_2^2 - x_3^2)^{2}}}}{x_1^2 + x_2^2}\frac{\partial}{\partial x_2} + exp^{\frac{-1}{(x_1^2 + x_2^2 - x_3^2)^{2}}} \frac{\partial}{\partial x_3} $$

In [77]:
# Importamos el módulo NumericalPoissonGeometry
from numpoisson.numpoisson import NumPoissonGeometry as npg
# Importamos el módulo PoissonGeometry
from poisson.poisson import PoissonGeometry as pg

# Instanciar el módulo NumericalPoissonGeometry con la dimensión y la variable a usar
npg3 = npg(3, 'x')
# Instanciar el módulo PoissonGeometry con la dimensión y la variable a usar
pg3 = pg(3, 'x')


In [78]:
# Definimos el bivector asociado a so(3)
P_sl2 = {(1, 2): '-x3', (1, 3): '-x2', (2,3): 'x1'}
# Definimos el campo vectorial W
W = {(1,): 'x1 * x3* exp(-1/(x1**2 + x2**2 - x3**2)**2) / (x1**2 + x2**2)',
     (2,): 'x2 * x3* exp(-1/(x1**2 + x2**2 - x3**2)**2) / (x1**2 + x2**2)',
     (3,): 'exp(-1 / (x1**2 + x2**2 - x3**2)**2)'}
# Calculamos la imagen del operador de cofrontera inducido por P_sl2 en el campo vectorial W
pg3.coboundary_operator(P_sl2, W)

{}

Para tener un ejemplo distinto a cero redefinimos el campo vectorial  

$$W = \frac{x_{1}exp^{\frac{-1}{(x_1^2 + x_2^2 - x_3^2)^{2}}}}{x_1^2 + x_2^2}\frac{\partial}{\partial x_1} + \frac{x_{2}exp^{\frac{-1}{(x_1^2 + x_2^2 - x_3^2)^{2}}}}{x_1^2 + x_2^2}\frac{\partial}{\partial x_2} + x_3 \frac{\partial}{\partial x_3} $$



In [79]:
# Redefinimos el campo vectorial W
W = {(1,): 'x1 * exp(-1/(x1**2 + x2**2 - x3**2)**2) / (x1**2 + x2**2)',
     (2,): 'x2 * exp(-1/(x1**2 + x2**2 - x3**2)**2) / (x1**2 + x2**2)',
     (3,): 'x3'}
# Calculamos la imagen del operador de cofrontera inducido por P_sl2 en el campo vectorial W
pg3.coboundary_operator(P_sl2, W)

{(1,
  2): '4*x1**2*x3*exp(-1/(x1**2 + x2**2 - x3**2)**2)/((x1**2 + x2**2)*(x1**2 + x2**2 - x3**2)**3) + 4*x2**2*x3*exp(-1/(x1**2 + x2**2 - x3**2)**2)/((x1**2 + x2**2)*(x1**2 + x2**2 - x3**2)**3) - x3*(4*x1**2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/((x1**2 + x2**2)*(x1**2 + x2**2 - x3**2)**3) - 2*x1**2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + x2**2)**2 + exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + x2**2)) - x3*(4*x2**2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/((x1**2 + x2**2)*(x1**2 + x2**2 - x3**2)**3) - 2*x2**2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + x2**2)**2 + exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + x2**2)) + x3',
 (1,
  3): 'x1*(4*x1*x2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/((x1**2 + x2**2)*(x1**2 + x2**2 - x3**2)**3) - 2*x1*x2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + x2**2)**2) - x2*(4*x1**2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/((x1**2 + x2**2)*(x1**2 + x2**2 - x3**2)**3) - 2*x1**2*exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + x2**2)**2 + exp(-1/(x1**2 + x2**2 - x3**2)**2)/(x1**2 + 

#### Evaluación de mapeo $\Pi_{\mathfrak{sl(2)}}^{\#}$

Sea $$\alpha = x_1 dx_1 + x_2 dx_2 + x_3 dx_3$$

Calculemos $\Pi_{\mathfrak{sl(2)}}^{\#}(\alpha)$ con ayuda del módulo simbólico.


In [80]:
# Definimos la 1-forma alpha
alpha = {(1,): 'x1', (2,): 'x2', (3,): '-x3'}
# Calculamos el morfismo sharp en alpha de manera simbólica
pg3.sharp_morphism(P_sl2, alpha)

{}

In [81]:
# Evaluamos el morfismo sharp en alpha en la malla R3_numpy_ramdon
npg3.num_sharp_morphism(P_sl2, alpha, R3_numpy_ramdon)

array([[[-3.58596071e-18],
        [-9.53418230e-18],
        [-1.48672163e-17]],

       [[ 5.77817354e-18],
        [-4.31852425e-18],
        [ 3.57786872e-18]],

       [[-5.73649145e-18],
        [ 1.78647634e-19],
        [ 2.39070826e-17]],

       ...,

       [[ 9.97306122e-19],
        [-2.72878829e-18],
        [ 5.50093040e-18]],

       [[ 2.64617839e-17],
        [ 1.04378106e-18],
        [-2.88628045e-18]],

       [[-2.84326348e-18],
        [-4.91594060e-17],
        [ 7.30539863e-19]]])

Ahora consideremos $\alpha= (x_2-x_3)dx_1 + (x_3-x_1)dx_2 + (x_1-x_2)dx_3$


In [82]:
# Redefinimos la 1-forma alpha
alpha = {(1,): 'x2-x3', (2,): 'x3-x1', (3,): 'x1-x2'}
# Calculamos el morfismo sharp en alpha de manera simbólica
pg3.sharp_morphism(P_sl2, alpha)

{(1,): 'x2*(x1 - x2) + x3*(-x1 + x3)',
 (2,): '-x1*(x1 - x2) - x3*(x2 - x3)',
 (3,): 'x1*(-x1 + x3) - x2*(x2 - x3)'}

In [83]:
# Evaluamos el morfismo sharp en alpha en la malla R3_list
npg3.num_sharp_morphism(P_sl2, alpha, R3_list)

array([[[-0.],
        [-1.],
        [-1.]],

       [[-1.],
        [-0.],
        [-1.]],

       [[ 1.],
        [ 1.],
        [-0.]]])

#### Evaluación del corchete de Poisson asociado a $\Pi_{\mathfrak{sl(2)}}$

Calculamos $$\{x_1, x_3\}_{\Pi_{\mathfrak{sl(2)}}} = -x_2$$

In [84]:
# Definimmos las funciones f y g
f = 'x1'
g = 'x3'
# Calculamos el corchete de Poisson de forma simbólica
pg3.poisson_bracket(P_sl2, f, g)

'-x2'

In [85]:
# Evaluamos el corchete de Poisson en la malla R3_list
npg3.num_poisson_bracket(P_sl2, f, g, R3_list)

array([ 0., -1.,  0.])

De igual manera para  

*   $\{x_1, x_2\}_{\Pi_{\mathfrak{sl(2)}}} = -x_3$
*   $\{x_2, x_3\}_{\Pi_{\mathfrak{sl(2)}}} = x_1$

In [86]:
# Definimmos las funciones f y g
f = 'x1'
g = 'x2'
# Calculamos el corchete de Poisson de forma simbólica
pg3.poisson_bracket(P_sl2, f, g)

'-x3'

In [87]:
# Evaluamos el corchete de Poisson en la malla R3_list
npg3.num_poisson_bracket(P_sl2, f, g, R3_list)

array([ 0.,  0., -1.])

In [88]:
# Definimmos las funciones f y g
f = 'x2'
g = 'x3'
# Calculamos el corchete de Poisson de forma simbólica
pg3.poisson_bracket(P_sl2, f, g)

'x1'

In [89]:
# Evaluamos el corchete de Poisson en la malla R3_list
npg3.num_poisson_bracket(P_sl2, f, g, R3_list)

array([1., 0., 0.])

#### Los métodos


| **num_bivector_field**        | **num_bivector_to_matrix**    | **num_poisson_bracket**           |
| :---------------------------: | :---------------------------: | :------------------------------:  |
| **num_hamiltonian_vf**        | **num_sharp_morphism**        | **num_coboundary_operator**       |
| **num_modular_vf**            | **num_curl_operator**         | **num_one_forms_bracket**         |
| **num_gauge_transformation**  | **num_linear_normal_form_R3** | **num_flaschka_ratiu_bivector**   |


### Referencias


* Miguel Evangelista-Alvarado, José C. Ruíz Pantaleón & P. Suárez-Serrato, <br/>
 [On Computational Poisson Geometry I: Symbolic Foundations](https://arxiv.org/pdf/1912.01746.pdf), <br/>
   arXiv:1912.01746 [math.DG] (2019)

* https://github.com/mevangelista-alvarado/NumericalPoissonGeometry/blob/master/README.md
